# CallFixV2 - Docker Version Alternative
# Cette version utilise un fichier .env au lieu des variables inline

version: '3.8'

services:
  app:
    image: node:18-alpine
    container_name: ticketv2-app
    working_dir: /app
    command: |
      command: sh -c "
        echo 'Installing dependencies...' &&
        npm install &&
        echo 'Installing client dependencies...' &&
        cd client && npm install && cd .. &&
        echo 'Waiting for database...' &&
        sleep 5 &&
        echo 'Setting up database...' &&
        node server/scripts/setup-db.js &&
        echo 'Starting application...' &&
        npm start
      "
    ports:
      - "7979:3000"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env.docker
    volumes:
      - .:/app
      - /app/node_modules
      - /app/client/node_modules
    networks:
      - ticketv2-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  db:
    image: postgres:15-alpine
    container_name: ticketv2-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: .njw6JQ*NKX8.vq!9R2!KfDMDB8Y_n
      POSTGRES_DB: ticketv2
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ticketv2-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    name: ticketv2-db-data

networks:
  ticketv2-network:
    name: ticketv2-network
    driver: bridge
